// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pelytyjonytekqdiwjri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlbHl0eWpvbnl0ZWtxZGl3anJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMjU1OTEsImV4cCI6MjA2NzYwMTU5MX0.pUzNiKuykr7Ci7qfEgEttJ3HbRMaq50bKrT54ped0Nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});